version: "3.8"

services:
  cron:
    container_name: cron-job
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - cron_net
    restart: unless-stopped

networks:
  cron_net:

volumes:
  postgres_data: